### ISSUE TITLE
Images from Camera folder are rotated

### ISSUE THREAD

**Issue by AravinthVelusamy** [akshay2211/PixImagePicker#10]
When selecting Images, the Images loaded from Camera folder are rotated. How to prevent rotation of images from Camera Folder?

**Comment by akshay2211** [comment]
Hello @AravinthVelusamy 
Use this in your adapter where you are showing the image

    File f = new File(list.get(position));
    Bitmap scaled = com.fxn.utility.Utility.getScaledBitmap(512,  com.fxn.utility.Utility.getExcifCorrectedBitmap(f));
    ((Holder) holder).iv.setImageBitmap(scaled);

kindly check #6 its already mentioned.
