### ISSUE TITLE
Not supporting 64 bit architecture

### ISSUE THREAD

**Issue by Punit234isummation** [akshay2211/PixImagePicker#101]
While uploading apk which have **pix** library,  getting error "This release is not compliant with the Google Play 64-bit requirement". So I guess, pix library is not supporting 64 bit architecture.

**Comment by akshay2211** [comment]
Hello @Punit234isummation 
there is no use of any native code in [PixImagePicker](https://github.com/akshay2211/PixImagePicker)
kindly look for any other library that uses Ndk , I'm sure that will be causing this problem
for more details kindly refer to [Support 64-bit architectures](https://developer.android.com/distribute/best-practices/develop/64-bit)
