### ISSUE TITLE
show only camera and hide Gallery fully.

### ISSUE THREAD

**Issue by sagarnayak** [akshay2211/PixImagePicker#108]
I want the user to click a fresh photo, and not allow the user to choose a picture from the gallery. is this possible with this library?

**Comment by sagarnayak** [comment]
if anyone want this feature you can use (https://github.com/sagarnayak/PixImagePicker) until this is available in @akshay2211 PixImagePicker.

**Comment by LebonNic** [comment]
Hi @akshay2211!

Do you plan to add this feature in PixImagePicker or not? Thanks in advance :)

Regards,
Nicolas

**Comment by iadcialim** [comment]
@akshay2211 Great lib here! So is this in the plan?

**Comment by iadcialim** [comment]
@akshay2211  created PR https://github.com/akshay2211/PixImagePicker/pull/223 for this
