### ISSUE TITLE
Video chooser

### ISSUE THREAD

**Issue by nikulcears** [akshay2211/PixImagePicker#109]
hii, when you will go for including video functionality. 
i have been checked you lib. and here is snippest for video as well in Constants.java
public static String[] PROJECTION = new String[]{
            MediaStore.Images.Media.DATA,
            MediaStore.Images.Media._ID,
            MediaStore.Images.Media.BUCKET_DISPLAY_NAME,
            MediaStore.Images.Media.BUCKET_ID,
            MediaStore.Images.Media.DATE_TAKEN,
            MediaStore.Images.Media.DATE_ADDED,
            MediaStore.Images.Media.DATE_MODIFIED,
            MediaStore.Files.FileColumns.MEDIA_TYPE,  //use for image and video
    };

 static String selection = MediaStore.Files.FileColumns.MEDIA_TYPE + "="
            + MediaStore.Files.FileColumns.MEDIA_TYPE_IMAGE
            + " OR "
            + MediaStore.Files.FileColumns.MEDIA_TYPE + "="
            + MediaStore.Files.FileColumns.MEDIA_TYPE_VIDEO;

static Uri URI = MediaStore.Files.getContentUri("external"); //used for image and video

and Utility.java
public static Cursor getCursor(Context context) {
    return context.getContentResolver().query(Constants.URI, Constants.PROJECTION,
//        null, null, Constants.ORDER_BY);
            Constants.selection, null, Constants.ORDER_BY);
    }

now it is including video files as well but we want your contributions as well. because you know well your project how to show thumb for video and all.
Thank you. hope you will upload code for video functionality very very soon.

**Comment by anandgaur22** [comment]
how to show a thumbnail to apply this code

**Comment by akshay2211** [comment]
Hello @nikulcears @anandgaur22 ,
Thanks for using [Pix](https://github.com/akshay2211/PixImagePicker),
Video support feature is integrated in the [latest release](https://github.com/akshay2211/PixImagePicker#download).
