### ISSUE TITLE
Support Fragment 

### ISSUE THREAD

**Issue by A86S** [akshay2211/PixImagePicker#11]
is this method  **`Pix.start`** supports support fragment

**Comment by sabieber** [comment]
Yes, i would also like a `start` Method that takes a `android.support.v4.app.Fragment`

**Comment by akshay2211** [comment]
Hello @A86S, @sabieber , Pix supports both the instances, AppcompatActivty and v4 fragment as well.

**Comment by akshay2211** [comment]
Hello @sabieber,
Thank you for pointing out the bug, I've updated it to v4 fragment in version 1.0.6

**Comment by sabieber** [comment]
Thanks for the extremely quick fix and new release. Tested it and now it works flawlessly with the Support Fragment instance.
