### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by ebekerman** [akshay2211/PixImagePicker#111]
How do I translate the displayed text, e.g. "Selected 1"?

**Comment by akshay2211** [comment]
Hello @ebekerman 
thank you for using pix
you can add this 
`<string name="pix_selected">Selected</string>`
in your own strings.xml to override this word

**Comment by ebekerman** [comment]
Thanks, this seems to work.
Any idea why the "Drag images up for gallery" is not overridden?
I tried with <string name="pix_bottom_message_without_video">

**Comment by akshay2211** [comment]
have you added setExcludeVideos(true)
default its false for both image and videos then you have to override 
`<string name="pix_bottom_message_with_video">Hold for video, tap for photo</string>`
if yes then only you have to override 
`<string name="pix_bottom_message_with_video">Hold for video, tap for photo</string>`
