### ISSUE TITLE
Audio Permission

### ISSUE THREAD

**Issue by ThinClient** [akshay2211/PixImagePicker#113]
Why does the latest version of PixImagePicker require permission to record audio. This might seem suspicious to users.

**Comment by akshay2211** [comment]
Because the latest version records video as well,
For the video it needs to take audio permission.

**Comment by ThinClient** [comment]
Okay, thanks. Is there a flag I can use to disable video recording capability and if there is, will this make it stop asking for audio permission.

**Comment by shobhitgupta1245** [comment]
seems like setExcludeVideos(true) disable video recording but it still ask for the micro phone permission

**Comment by shobhitgupta1245** [comment]
created pull request for the same 
https://github.com/akshay2211/PixImagePicker/pull/115

**Comment by ThinClient** [comment]
Is there a way to set this when picking a single picture? The code for picking a single picture is
Pix.start(context,Options.init().setRequestCode(100)). Is there a way to call functions on the options object before picking a single picture. Refer me to documentation that has this details if there is any, I haven't found one.

**Comment by shobhitgupta1245** [comment]
I think this will depend on the the video flag that you enable/disable on options. Though you can change options everytime before invoking it.

**Comment by akshay2211** [comment]
`Pix.start(context,Options.init().setRequestCode(100))`
is the minimal config to to start Pix
video option is default on in this , to take only single picture 
you can use this.
`Pix.start(context,Options.init().setRequestCode(100).setExcludeVideos(true))`

**Comment by ThinClient** [comment]
Thanks. The new version is sleek.
