### ISSUE TITLE
it should not be ask for microphone permission if ExcludeVideos is set to false

### ISSUE THREAD

**Issue by shobhitgupta1245** [akshay2211/PixImagePicker#114]

**Comment by shobhitgupta1245** [comment]
I think you will need to set Audio.off on cameraview

**Comment by akshay2211** [comment]
Thanks for the PR
the issue is resolved in the latest [release](https://github.com/akshay2211/PixImagePicker#download)

**Comment by shobhitgupta1245** [comment]
@akshay2211  Are you planning to move to media store since getExternalDir() is deprecated now

**Comment by shobhitgupta1245** [comment]
@akshay2211  Thanks :)

**Comment by ThinClient** [comment]
You guys are awesome thanks for resolving the issue.

**Comment by akshay2211** [comment]
Make sure to star the library 😊
