### ISSUE TITLE
CameraX integration

### ISSUE THREAD

**Issue by marcauberer** [akshay2211/PixImagePicker#116]
Hi threre,
first of all, thanks for you awesome library!
I just wanted to ask, if you're planning to migrate your project to [CameraX](https://developer.android.com/jetpack/androidx/releases/camera)?
Would appreciate it!

**Comment by Parag2385** [comment]
Hello, @marcauberer I've implemented the exact same UI with CameraX and published it. you can check it out here: https://github.com/Parag2385/Picker

Also, @akshay2211 Thank you so much for the inspiration. I'll be glad if you could check it out as well and let me know if I can improve it anyway.

**Comment by marcauberer** [comment]
@Parag2385 thanks for the link. I'll try it out!
