### ISSUE TITLE
Fragment issue

### ISSUE THREAD

**Issue by Sohit-Sharma** [akshay2211/PixImagePicker#118]
It's not giving me onActivityResult on fragment. What's the code to get the onActivityResult on fragment. please tell me asap.

**Comment by marcauberer** [comment]
There is no `onActivityResult` or respectively `onFragmentResult` method existing. You would have to use interfaces or pass your activity object to the fragment and call the activity methods from the fragment manually.

**Comment by akshay2211** [comment]
Hello @Sohit-Sharma 
provide the version you are using for activity, fragment and appcompat in your gradle

**Comment by Sohit-Sharma** [comment]
My gradle version is 5.6.4 and gradle plugin version is 3.6.2

**Comment by akshay2211** [comment]
I wasn't asking for that, 
i was asking for the dependency version 
something like this in your gradle file
` implementation 'androidx.appcompat:appcompat:1.1.0'`
any way if you are using any alpha version kindly use the stable one
as the onActivityResult method is deprecated in new  alpha versions.

**Comment by kashifJawed90** [comment]
implementation 'androidx.appcompat:appcompat:1.1.0'

using nav controller one of fragment use Pix and not getting result in either of them

@Override
    public void onActivityResult(int requestCode, int resultCode, Intent imageReturnedIntent)

@Override
    public void startIntentSenderForResult(IntentSender intent, int requestCode, @Nullable Intent fillInIntent, int flagsMask, int flagsValues, int extraFlags, @Nullable Bundle options) throws IntentSender.SendIntentException

@Override
    public void startActivityForResult(Intent intent, int requestCode)
