### ISSUE TITLE
low resolution video

### ISSUE THREAD

**Issue by ShankyPatel** [akshay2211/PixImagePicker#121]
hi is there anyway i can record low resolution video. so that wont need to compress the video every time.

**Comment by akshay2211** [comment]
Hi @ShankyPatel 
for now there is no such way in existing library.

**Comment by ShankyPatel** [comment]
will appreciate if you add this feature in future as currently its working on default settings of camera which records large size file so the option i have is ffmpeg only to reduce size which will increase my app size.

**Comment by akshay2211** [comment]
for now due to lack of resources, i am not planing to add any feature in near future.

**Comment by ShankyPatel** [comment]
Hi Akshay just checked your library.
Following library that you have used,
    implementation 'com.otaliastudios:cameraview:2.6.2'
 does provide setting video size by keeping setting cameraVideoSizeMaxHeight and cameraVideoSizeMaxWidth. So you may add this options in your library in future also wont take much time.

**Comment by ShankyPatel** [comment]
don't set video size from xml it doesnt work well, leads to crash. Size selector you have used to set the video size does work.
