### ISSUE TITLE
show images only

### ISSUE THREAD

**Issue by ShankyPatel** [akshay2211/PixImagePicker#122]
Hi Akshay, is there anyway to show just images in the images grid as i dont want video to be selected ?

**Comment by akshay2211** [comment]
Hello @ShankyPatel 
just add `setExcludeVideos(true) ` in Options object
to exclude videos and only use images
for more options kindly visit the the [documentation](https://github.com/akshay2211/PixImagePicker#usage).

**Comment by ShankyPatel** [comment]
hi akshay i meant how to exclude videos from swipe up image list not remove videos thoroughly.

**Comment by akshay2211** [comment]
@ShankyPatel you can pull the library module in your project and customize the necessary changes you need.
