### ISSUE TITLE
RecyclerView Error an androidx

### ISSUE THREAD

**Issue by alijkdkar** [akshay2211/PixImagePicker#125]
sync Error  on RecyclerView on androidx

**Comment by akshay2211** [comment]
Hi @alijkdkar,
Thanks for using [Pix](https://github.com/akshay2211/PixImagePicker)
this issue is not related to the library itself.
still, if you are using an older version try upgrading to the latest one
and try posting the bug on StackOverflow with hashtag #PixImagePicker for androidx sync
