### ISSUE TITLE
Increase otaliastudios lib to 2.6.3

### ISSUE THREAD

**Issue by 73k05** [akshay2211/PixImagePicker#128]
Hi @akshay2211  thank you for the great work here,

could you change
`implementation 'com.otaliastudios:cameraview:2.6.2'`
to
`implementation 'com.otaliastudios:cameraview:2.6.3'`

I have a few crashes on this dependency, I would like to see if it's fixed in the last version.

https://github.com/73k05/PixImagePicker/commit/b417070fb9e5c95ee7f67a9b69c599e785112fa8

**Comment by 73k05** [comment]
Here is a feed that might interest you, the bug is coming from your integration:
https://github.com/natario1/CameraView/issues/921

**Comment by akshay2211** [comment]
Hello @73k05 
Thankyou for your valuable feedback
the dependencies are updated now and ill soon release a new version for it.
