### ISSUE TITLE
Bad Scroll Performance in recent images list

### ISSUE THREAD

**Issue by sabieber** [akshay2211/PixImagePicker#13]
Hi,

I experience a lot of stuttering in the recent images list (when pulling the image bar up).
In contrast to that the performance when scrolling the horizontal image bar is superb.

Could this be improved upon?

**Comment by akshay2211** [comment]
Hello @sabieber,
this will take a bit time as I have to look a bit deep into it,
I will resolve it as soon as I get enough time.

**Comment by sabieber** [comment]
Thats totally okay, thanks for looking into the issue

**Comment by sabieber** [comment]
Seems to be mainly the Image loading. Maybe a switch to [Glide](https://github.com/bumptech/glide) would improve the performance.

**Comment by sabieber** [comment]
I am working on a PR switching Fresco out and Glide in as it seems to speed things up quite a lot.
If you want to stick with Fresco for whatever reason i will keep it in my fork.

**Comment by akshay2211** [comment]
Hello @sabieber, 
Thank you for helping me out in improving pix,
your pull request is been merged, there was a bug in that, as the sticky headers were not working,
its been fixed and updated,
kindly refer the latest version 1.0.7

**Comment by sabieber** [comment]
Hi @akshay2211,

thanks for merging the PR and huge thanks for fixing the sticky headers bug, I must have missed that while testing my changes.

Only one problem: After upgrading to 1.0.7 in my app the build cant resolve `start` and `IMAGE_RESULTS`. Did this result from an error with the gradle changes or something i messed up?

**Comment by akshay2211** [comment]
Hey @sabieber,
Thank you for pointing 1.0.7 bug , minifyEnabled property renamed all the packages in jar so nothing was accessible from pix.java.
Its now resolved, try version 1.0.8.

**Comment by sabieber** [comment]
Works like a charm! Thanks for the fix.
