### ISSUE TITLE
i do not understand how to use this ?

### ISSUE THREAD

**Issue by tirumala007** [akshay2211/PixImagePicker#130]
i have added the dependency. After that i do not know what to do ?
i am getting error when adding the line 
 Pix.start(Context,  RequestCode,  NumberOfImagesToSelect);     
at Context. where do put this line. i want to select only 3 images. help me.

**Comment by akshay2211** [comment]
hi @tirumala007 
kindly go through the docs 
[https://github.com/akshay2211/PixImagePicker#usage](https://github.com/akshay2211/PixImagePicker#usage)
