### ISSUE TITLE
Hardcoded strings

### ISSUE THREAD

**Issue by sabieber** [akshay2211/PixImagePicker#14]
Hi,

I want to use your library in an app with multiple languages but found some untranslatable strings in the sources.

eg.: `android:text="Drag images up for gallery"`
These should be moved to the `strings.xml` file

**Comment by akshay2211** [comment]
done in the updated release 1.0.6

**Comment by sabieber** [comment]
Thanks for the extremely quick fix, much appreciated. Works like a charm.
