### ISSUE TITLE
not working in sdk level 30 

### ISSUE THREAD

**Issue by vishal14321432** [akshay2211/PixImagePicker#142]
Please update the code when capturing image from camera in sdk level 30 app is crashing  but working fine when picking images from gallery 
this line is already added in manifestl̥ file 
android:requestLegacyExternalStorage="true"
thanks in advance

**Comment by akshay2211** [comment]
Hi @vishal14321432 
Thanks for tying out Pix
Try with the latest version of pix.
`implementation  'com.fxn769:pix:1.5.3'`

**Comment by vishal14321432** [comment]
i am using the update version 1.5.3   please check it out app is still crashing when capture image...

  `java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
        at com.fxn.pix.Pix$8$1.onFileReady(Pix.java:455)
`

**Comment by AniketKonnections** [comment]
any update on this?

**Comment by anasmadrhar** [comment]
Any update on this? +2

**Comment by anasmadrhar** [comment]
according to the documentation, getExternalStoragePublicDirectory deprecated in Android Q that's probably why the app fail in creating the file in the destination directory. maybe we should change it to something else.

**Comment by mf-mindcrewtech** [comment]
Any update @akshay2211 ?? Please let me know, facing same issue.

**Comment by jasonbekolay** [comment]
I'm affected by this issue as well. Happy to work on a potential resolution if that would be helpful!

**Comment by akshay2211** [comment]
Hi @jasonbekolay, you are most welcome to contribute here.
the current problem is the library does not support scoped storage yet.
that's why is not working properly in API level 30.

**Comment by akshay2211** [comment]
Hello @vishal14321432 
This issue is been resolved in the latest [PixImagePicker version 1.5.5](https://github.com/akshay2211/PixImagePicker#download)
