### ISSUE TITLE
Question : Is there any way to use this as WhatsApp tab camera ?

### ISSUE THREAD

**Issue by mf-mindcrewtech** [akshay2211/PixImagePicker#150]

**Comment by marcauberer** [comment]
Nope. You you would need to recompile the installable WhatsApp package.

**Comment by mf-mindcrewtech** [comment]
@marcauberer what I meant this https://raw.githubusercontent.com/goody-h/ResidingTab/master/images/whatsapp_shot.png

Not to decompile some WhatsApp package

**Comment by marcauberer** [comment]
Yes, but this camera view is part of the WhatsApp package.

**Comment by mf-mindcrewtech** [comment]
Okay thanks
