### ISSUE TITLE
How to set it get Image only or video only ?

### ISSUE THREAD

**Issue by gamalragab21** [akshay2211/PixImagePicker#157]

**Comment by akshay2211** [comment]
Hello @gamalragab21 
kindly refer to the [Usage Section](https://github.com/akshay2211/PixImagePicker#usage) in the documentation
currently, you can either use both images and videos, or use only images by the method
`  .setExcludeVideos(false)                                       //Option to exclude videos`

**Comment by gamalragab21** [comment]
ok,but i want image only...

**Comment by gamalragab21** [comment]
Ok
But I want Vidoes Only...!"
