### ISSUE TITLE
image rotated while displaying after capturing in camera

### ISSUE THREAD

**Issue by Abdul96881** [akshay2211/PixImagePicker#163]
image rotated while displaying after capturing in camera it should have option to set display orientation after capturing image from camera
![device-2021-01-21-120805](https://user-images.githubusercontent.com/20418106/105302643-5a8ea880-5be1-11eb-8df4-e3beefae119f.png)

**Comment by jetsekoopmans** [comment]
I'm having the same issue...

**Comment by Abdul96881** [comment]
is there any update from admin

**Comment by Abdallah-Abdelazim** [comment]
Same issue happening with me

**Comment by eduardoyuren** [comment]
Same issue, Is there any update?

**Comment by eduardoyurencb** [comment]
Same issue, Is there any update?

**Comment by Abdul96881** [comment]
updated adapter class

package com.fxn.adapters

import android.R.attr.bitmap
import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Matrix
import android.media.ExifInterface
import android.media.ThumbnailUtils
import android.net.Uri
import android.os.Build
import android.provider.MediaStore
import android.util.Log
import android.util.Size
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.ImageView
import androidx.core.graphics.drawable.RoundedBitmapDrawableFactory
import androidx.recyclerview.widget.RecyclerView
import com.fxn.pixsample.R
import java.io.File
import java.io.IOException
import java.nio.file.Files
import java.util.*


class MyAdapter(private val context: Context) : RecyclerView.Adapter<RecyclerView.ViewHolder>() {

    private val list = ArrayList<String>()

    fun addImage(list: List<String>) {
        this.list.clear()
        this.list.addAll(list)
        notifyDataSetChanged()
    }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
        val v = LayoutInflater.from(parent.context).inflate(R.layout.image, parent, false)
        return Holder(v)
    }

    override fun onBindViewHolder(holder: RecyclerView.ViewHolder, position: Int) {
        //Uri imageUri = Uri.fromFile(new File(list.get(position)));// For files on device
        val f = File(list[position])
        val len = f.absolutePath.length
        Log.e("check", "f.absolutePath.subSequence(len-3,len)  " + f.absolutePath.subSequence(len - 3, len))
        val bitmap = if (f.absolutePath.subSequence(len - 3, len).equals("mp4")) {
            (holder as Holder).play.visibility = View.VISIBLE
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                ThumbnailUtils.createVideoThumbnail(f, Size(500, 500), null)
            } else {
                ThumbnailUtils.createVideoThumbnail(f.absolutePath, MediaStore.Video.Thumbnails.MINI_KIND)
            }
        } else {
            (holder as Holder).play.visibility = View.GONE


            BitmapFactory.decodeFile(f.absolutePath)
            //BitmapDrawable(context.resources, f.absolutePath).bitmap
        }
        val ei = ExifInterface(f.absolutePath)
        val orientation: Int = ei.getAttributeInt(ExifInterface.TAG_ORIENTATION,
                ExifInterface.ORIENTATION_UNDEFINED)

        var rotatedBitmap: Bitmap? =null
        when (orientation) {
            ExifInterface.ORIENTATION_ROTATE_90 -> rotatedBitmap= rotateImage(bitmap!!, 90f)
            ExifInterface.ORIENTATION_ROTATE_180 -> rotatedBitmap= rotateImage(bitmap!!, 180f)
            ExifInterface.ORIENTATION_ROTATE_270 -> rotatedBitmap= rotateImage(bitmap!!, 270f)
            ExifInterface.ORIENTATION_NORMAL ->rotatedBitmap= bitmap!!
            else -> rotatedBitmap= bitmap!!
        }
        val roundedBitmapDrawable = RoundedBitmapDrawableFactory.create(context.resources, rotatedBitmap)

        val roundPx = rotatedBitmap!!.width.toFloat() * 0.06f
        roundedBitmapDrawable.cornerRadius = roundPx
        holder.iv.setImageDrawable(roundedBitmapDrawable)
        holder.iv.setOnClickListener {
            val intent = Intent(Intent.ACTION_VIEW, Uri.parse(f.absolutePath))
            try {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    intent.setDataAndType(Uri.parse(f.absolutePath), Files.probeContentType(f.toPath()))
                } else {
                    intent.data = Uri.parse(f.absolutePath)
                }
            } catch (e: IOException) {
                e.printStackTrace()
            }
            context.startActivity(intent)
        }
        /*Bitmap scaled = com.fxn.utility.Utility.getScaledBitmap(
            500f, com.fxn.utility.Utility.rotate(d,list.get(position).getOrientation()));*/
    }
    fun rotateImage(source: Bitmap, angle: Float): Bitmap? {
        val matrix = Matrix()
        matrix.postRotate(angle)
        return Bitmap.createBitmap(source, 0, 0, source.width, source.height,
                matrix, true)
    }

    override fun getItemCount() = list.size

    inner class Holder(itemView: View) : RecyclerView.ViewHolder(itemView) {
        var iv: ImageView = itemView.findViewById(R.id.iv)
        var play: ImageView = itemView.findViewById(R.id.play)
    }
}
