### ISSUE TITLE
bottom message wrong for Options.Mode.Picture

### ISSUE THREAD

**Issue by nikky76342** [akshay2211/PixImagePicker#165]
Bottom message on camera screen is showing as "Hold for video, tap for photo" when using Options.Mode.Picture, whereas it should actually show only "Tap for photo"

**Comment by joey-harward** [comment]
Yes I agree. Or maybe this text could be overridden in xml or set through Options builder?

**Comment by nikky76342** [comment]
No, there is no method in Options Builder to set text to that textview

**Comment by joey-harward** [comment]
Right I know there isn't a method to set it. I was suggesting that developers possibly add this to the Options builder to fix this issue :)

**Comment by jeanraymonddaher** [comment]
any updates on this ?
it would be nice to disable the long tap gesture too for the icon changing to video in photo mode

**Comment by jeanraymonddaher** [comment]
@joey-harward 
use implementation  'com.github.akshay2211:pix:master'
inside your gradle file and you should be good to go
