### ISSUE TITLE
Why we are asking mic permission for camera

### ISSUE THREAD

**Issue by praslnx8** [akshay2211/PixImagePicker#17]
1. We are asking mic permission for Camera
2. On Camera permission with permission result success the pix activity is not opening.

**Comment by akshay2211** [comment]
Hello @praslnx8
for 1st pix asks for mic permission as its the default permission for the camera dependency used in pix.
and for 2nd can you please provide a bit more info like the code snippet that you are using.

**Comment by sabieber** [comment]
We could disable the first one by adding `app:ckPermissions="picture"` to the CameraView in layout xml. See this for reference: https://github.com/CameraKit/camerakit-android/issues/297

**Comment by akshay2211** [comment]
Thankyou @sabieber for the quick help
@praslnx8 1st one is resolved in new update 1.0.9
and for the second one check [`add this method in you activity or fragment`](https://github.com/akshay2211/PixImagePicker#permission-handling)

**Comment by praslnx8** [comment]
Thanks @akshay2211 Akshay and @sabieber

**Comment by adeelahmad8127** [comment]
@akshay2211 You can set off Audio Permission by setting Camera View. cameraPreview.setAudio(Audio.OFF);
