### ISSUE TITLE
Image Quality 

### ISSUE THREAD

**Issue by mukul-prabhakar** [akshay2211/PixImagePicker#177]
.setImageQuality(ImageQuality.LOW) was available in previous version 
but in latest version its not possible 
Do have any suggestion to achieve this? I'm stuck in my current project

**Comment by akshay2211** [comment]
Hello @mukul-prabhakar,
You have to manage image quality at the application end only, there is no need to provide this functionality in the library.
you can achieve this by using a library like [Compressor](https://github.com/zetbaitsu/Compressor)
