### ISSUE TITLE
Drawables don't have the color .xml

### ISSUE THREAD

**Issue by felipe9962** [akshay2211/PixImagePicker#186]
The icon don't match the color of colors.xml because the color is manually writted, not reference of the colors.xml like the photo.
![Captura de pantalla 2021-06-23 a las 9 50 07](https://user-images.githubusercontent.com/55816143/123057935-959f3d00-d408-11eb-8569-86416f565711.png)

**Comment by felipe9962** [comment]
And if you would add a method in Options to turn off the CameraView sound that would be great!

**Comment by akshay2211** [comment]
Hello @felipe9962 is resolved in the new version [1.6.2](https://github.com/akshay2211/PixImagePicker#download)
