### ISSUE TITLE
FATAL EXCEPTION when calling addPixToActivity

### ISSUE THREAD

**Issue by ThinClient** [akshay2211/PixImagePicker#191]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.Display.getRealMetrics(android.util.DisplayMetrics)' on a null object reference
        at io.ak1.pix.helpers.CameraXManager.bindCameraUseCases(CameraXManager.kt:62)
        at io.ak1.pix.helpers.CameraXManager.setUpCamera$lambda-0(CameraXManager.kt:55)
        at io.ak1.pix.helpers.CameraXManager.lambda$saIgVXdcX8hBqOG6Idaj-FlC7bY(Unknown Source:0)

**Comment by 73k05** [comment]
@ThinClient I have the same error when calling addPixToActivity before the view has been attached to windows when calling in onCreate() right?

**Comment by ThinClient** [comment]
yeah right @73k05. This is my code:
```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_pix_image_picker)
        supportActionBar?.hide()
        var preselectedUrls = ArrayList<Uri>()
        if (intent.hasExtra(EXTRA_PRESELECTED_URLS)) {
            preselectedUrls = intent.getParcelableArrayListExtra<Uri>(EXTRA_PRESELECTED_URLS) as ArrayList<Uri>
        }
        var countLimit = 9
        if (intent.hasExtra(EXTRA_COUNT_LIMIT)) {
            countLimit = intent.getIntExtra(EXTRA_COUNT_LIMIT, 9)
        }
        val options = Options().apply {
            ratio = Ratio.RATIO_AUTO                
            count = countLimit                     
            spanCount = 4                           
            path = "Pix/Camera"                     
            isFrontFacing = false                  
            mode = Mode.Picture                     
            flash = Flash.Auto                     
            preSelectedUrls = preselectedUrls       
        }
        addPixToActivity(R.id.container, options) {
            when (it.status) {
                PixEventCallback.Status.SUCCESS -> {
                    val intent = Intent()
                    intent.putParcelableArrayListExtra(FormFragment.EXTRA_PICTURES, ArrayList(it.data))
                    setResult(Activity.RESULT_OK, intent)
                    finish()
                }
                PixEventCallback.Status.BACK_PRESSED -> {
                  // do something
                }
            }
        }
    }
```

**Comment by 73k05** [comment]
Hi @ThinClient,

this needs to be permanently fix by core team but here is the workaround you can use in the meantime:

**Call addPixToActivity after view is attached to window in `onAttachedToWindow()`** See the following example:

```
 override fun onAttachedToWindow() {
        super.onAttachedToWindow()
        showCameraFragment()
    }
  ```
  And in `showCameraFragment()` your `addPixToActivity`code. Let me know if that works
  
  Good Luck

**Comment by ThinClient** [comment]
@73k05  yes it does seem to work when I put everything in onAttachedToWindow(). Thanks.

**Comment by mukul-prabhakar** [comment]
addPixToActivity(R.id.container, option)

in this is container the id for the root view of 

What if i want to initiate pix picker when i click on button

**Comment by ThinClient** [comment]
@mukul-prabhakar  yes it is the id of the root view. There are multiple approaches you can use to add pix to your activities as show in the tutorials. My approach is to start an activity whose sole fragment is pix image picker. If you are clicking a button, maybe you could add pix using the navigation component approach.

**Comment by mukul-prabhakar** [comment]
val options = Options().apply {
            ratio = Ratio.RATIO_AUTO                
            count = 1                 
            spanCount = 4                           
            path = "Pix/Camera"                     
            isFrontFacing = false                  
            mode = Mode.Picture                     
            flash = Flash.Auto                     
            preSelectedUrls = preselectedUrls       
        }

 addPixToActivity(R.id.container, options) {
            when (it.status) {
                PixEventCallback.Status.SUCCESS -> {
                  // getting my results
                }
                PixEventCallback.Status.BACK_PRESSED -> {
                  // do something
                }
            }
        }


With comparison to previous version
I initiate pix picker when click on button in my activity [select single/multiple images]
1. On Callback event is called it receives the Uri of selected image but window doesn't get dismissed. Is there any way?
2. On Clicking camera it clicks picture but doesn't sent show preview or get dismissed on its own

**Comment by ThinClient** [comment]
@mukul-prabhakar there is a tutorial for this. First download the code for pix examples and explore it. You will get the hang of it after that. Here we are trying to get the issues with pix fixed not FAQs.

**Comment by akshay2211** [comment]
Seems like I need to write a detailed documentation to use the new version
@73k05 Thanks for the PR
@ThinClient will try to release a new version with this fixed soon
@mukul-prabhakar for 1 & 2 there are callbacks and you need to handle both of them on your own, as @ThinClient mentioned please refer to the sample app.

**Comment by ahuamana** [comment]
I used like this on viewBinding wiht Activity

` addPixToActivity(android.R.id.content ,options)
        {
            when (it.status)
            {
                PixEventCallback.Status.SUCCESS -> {

                    Log.e("TAG","CAMERA RESULT: SUCCESS")

                }//use results as it.data

                PixEventCallback.Status.BACK_PRESSED -> {

                    Log.e("TAG","CAMERA RESULT: FAIL")

                }// back pressed called
            }
        }`
