### ISSUE TITLE
Toast message while image taken from camera

### ISSUE THREAD

**Issue by mukul-prabhakar** [akshay2211/PixImagePicker#195]
Need to stop/dismiss toast message

**Comment by Syizuril** [comment]
is there any option or solution to get dismiss of it?

**Comment by Syizuril** [comment]
> Need to stop/dismiss toast message

Is there any option or solution to get dismiss of it?

**Comment by pmrzygweb** [comment]
👍

**Comment by pmrzygweb** [comment]
When this will be fixed?

**Comment by Yunhao0799** [comment]
I don't think is a default behaviour, doesn't show for me
