### ISSUE TITLE
JCenter is at end of life

### ISSUE THREAD

**Issue by LuisBorm** [akshay2211/PixImagePicker#197]
As JCenter is at end of life, is there any migration to mavenCenteral?

**Comment by akshay2211** [comment]
@LuisBorm PixImagePicker has already migrated from jcenter to mavencentral
The latest version of [PixImagePicker 1.6.2](https://github.com/akshay2211/PixImagePicker#download) is available on mavencentral

**Comment by monali0521** [comment]
@akshay2211  how can i differentiate image and video from it.data?

 it.data.forEach {
                        Log.e(TAG, "showCameraFragment: ${it.path}")
                    }
                    resultsFragment.setList(it.data)
                }

**Comment by akshay2211** [comment]
#196 replied
