### ISSUE TITLE
Getting Failed to resolve: io.fotoapparat.fotoapparat:library:2.2.0

### ISSUE THREAD

**Issue by praslnx8** [akshay2211/PixImagePicker#21]
implementation 'com.fxn769:pix:1.0.10' throws Failed to resolve: io.fotoapparat.fotoapparat:library:2.2.0

**Comment by holparb** [comment]
I'm still getting this issue with 1.2.1, but for a different fotoapparat version:
Failed to resolve: io.fotoapparat.fotoapparat:library:2.3.1

Did I miss something?

**Comment by akshay2211** [comment]
Hello @praslnx8 have you added this dependency to your build.gradle
`repositories {
  maven { url 'https://jitpack.io' }
}`

if not, can you provide the gradle file that you are using.

**Comment by praslnx8** [comment]
After adding repositories { maven { url 'https://jitpack.io' } } is works fine. **Add it to the read me**.
