### ISSUE TITLE
Remove Photo capture Toast

### ISSUE THREAD

**Issue by pmrzygweb** [akshay2211/PixImagePicker#219]
really need to remove the toast for photo captured successfully
I saw this PR for remove of video capture toast - https://github.com/akshay2211/PixImagePicker/pull/194/files
Can we remove a toast for photo capture as well? Thanks

**Comment by pmrzygweb** [comment]
@akshay2211 Is this repo maintained at all?

**Comment by akshay2211** [comment]
> @akshay2211 Is this repo maintained at all?

It is maintained, but as a single contributor, updating it frequently is not possible.
I will update it in the next few weeks,
If you want it to use it with your desired changes please feel free to use its source in your app.
Thanks.

**Comment by iadcialim** [comment]
Hi @akshay2211 There are some PRs since June. Please check when you the time. Thanks

**Comment by akshay2211** [comment]
Hi @pmrzygweb 
this issue is been resolved in the new [version](https://github.com/akshay2211/PixImagePicker#download)
