### ISSUE TITLE
"Missing required view with ID" error if using gradle 7.0.2

### ISSUE THREAD

**Issue by thawri1** [akshay2211/PixImagePicker#221]
I upgrade gradle to 7.0.2. after taht i get this error:
java.lang.NullPointerException: Missing required view with ID: com.wisgoon.wismediapicker:id/controls_layout
        at io.ak1.pix.databinding.ControlsLayoutBinding.bind(ControlsLayoutBinding.java:125)
        at io.ak1.pix.databinding.GridLayoutBinding.bind(GridLayoutBinding.java:159)
        at io.ak1.pix.databinding.FragmentPixBinding.bind(FragmentPixBinding.java:76)
        at io.ak1.pix.databinding.FragmentPixBinding.inflate(FragmentPixBinding.java:62)
        at io.ak1.pix.PixFragment.onCreateView(PixFragment.kt:105)

**Comment by rahul-hexalitics** [comment]
Remove Merge tag from top of the included layout

**Comment by iadcialim** [comment]
@rahul-hexalitics can show the code? cos I tried, it still crashes

**Comment by rahul-hexalitics** [comment]
Under the pix module in layout directory grid_layout.xml, controls_layout.xml, permissions_layout.xml and video_counter_layout.xml are starting with <merge...> tag.
remove the merge like, in 
**grid_layout.xml**
from
`<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <FrameLayout
        android:id="@+id/grid_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
...
        </FrameLayout>
        </merge>`
        
        **To**
        
        `<?xml version="1.0" encoding="utf-8"?>
    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
        android:id="@+id/grid_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
...
        </FrameLayout>`
