### ISSUE TITLE
Remove the toast for photo captured successfully

### ISSUE THREAD

**Issue by faniabdullah** [akshay2211/PixImagePicker#231]
Hi @akshay2211 There are some PRs since June. Please check when you have the time. Thanks

I saw this PR for remove of video capture toast - https://github.com/akshay2211/PixImagePicker/pull/194/files
Can we remove a toast for photo capture as well? Thanks

**Comment by Raghuveer-hub** [comment]
Dear @akshay2211 thanks for your efforts in bringing up this library,Can you please remove the toast and resubmit the gradle plugin.

**Comment by akshay2211** [comment]
Hello @faniabdullah and @Raghuveer-hub 
Thank you for using Pix, 
The above PR is been merged and please new version is been released [1.6.3](https://github.com/akshay2211/PixImagePicker#download)

**Comment by dineshkumarappdeveloper** [comment]
Hey Akshay!. Thanks for the fix
