### ISSUE TITLE
Ask again permission not working

### ISSUE THREAD

**Issue by Prashantilluminz** [akshay2211/PixImagePicker#237]
I deny the permission on pix fragment and ask again pop up comes but when i click on ask again nothing happens. Please look into this. Permissions  deny scenarios are not working properly.

**Comment by sambhav2358** [comment]
When you deny a permission, android feels the too is trying to disturb the user by again and again asking for permissions. This is not an issue with the library.

**Comment by Prashantilluminz** [comment]
User feeling struck there is it right?

**Comment by sambhav2358** [comment]
It happens only if user permanently denies the permission. Otherwise it works fine
