### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by BenCherif** [akshay2211/PixImagePicker#25]
Hi bro ,
i would like to suggest to add "pick/record video" as new feature ,it will be great if you add this .
Kind regards

**Comment by koeks525** [comment]
I would also like a pick video feature as well... that would be really awesome.

**Comment by akshay2211** [comment]
Hello @BenCherif , @koeks525 ,
I am really not able to take out time these days for a major update.
I'll try to add this functionality by end of next month.

**Comment by BenCherif** [comment]
thanks bro

**Comment by bhavifm** [comment]
Hi @akshay2211 bro wonderful library thank you,  even i would also want video feature.

**Comment by koeks525** [comment]
Hey @akshay2211, still loving your library... love the new changes you have introduced. Has there been any update regarding the video picking feature?

**Comment by Qism0** [comment]
I see this commit on the branch mark1 https://github.com/akshay2211/PixImagePicker/commit/5056b2a6635c6fbf95a66f8e9e6f9351baf8382f 
I can help implementing this feature ;-) But I will do it on my fork which has not been merged yet and might never been...

**Comment by akshay2211** [comment]
Hey @Qism0 
it's just that you changed the package name in your fork, so won't be able to merge it.
you can pull again, I am a bit busy these days, I would be glad to get some help on the new features.

**Comment by Qism0** [comment]
Morning @akshay2211  Thank you for great support and quick reply!

I updated the package name and made a new [PR](https://github.com/akshay2211/PixImagePicker/pull/63)

Qism0

**Comment by akshay2211** [comment]
Hello @BenCherif @bhavifm 
Thanks for using [Pix](https://github.com/akshay2211/PixImagePicker),
Video support feature is integrated in the [latest release](https://github.com/akshay2211/PixImagePicker#download).
