### ISSUE TITLE
Reproducible: CRASH DETECTED

### ISSUE THREAD

**Issue by iv47** [akshay2211/PixImagePicker#27]
**Steps to reproduce**
1. Launch the camera by calling ` Pix.start(Context, RequestCode);` 
2. Double tap the circle camera button to take a picture.
3. App crashes

Tested on a Google Pixel 2 XL

**Logs**
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at com.fxn.pix.Pix$8$1.invoke(Pix.java:439)
        at com.fxn.pix.Pix$8$1.invoke(Pix.java:436)
        at io.fotoapparat.result.PendingResult$whenAvailable$1.run(PendingResult.kt:81)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
07-26 11:52:20.439 18640-18640/com.neek.tech.superstrikers E/my pick saved: android.graphics.Bitmap@384db81    ->  219

**NOTE**  
Crash happens with Rear or Front camera.

**Comment by jesualex** [comment]
i have the same problem only in a LG K10 LTE android 6.0

any solution?

**Comment by akshay2211** [comment]
@iv47, @jesualex Thanks for pointing out the bug.
It is been resolved in the latest version [1.2.4](https://github.com/akshay2211/PixImagePicker#download)

**Comment by iv47** [comment]
@akshay2211 @jesualex  Just bumped my project version to `1.2.4` and tested this using the **Steps to reproduce** I posted earlier and it doesn't occur anymore!

**Comment by akshay2211** [comment]
Thanks, @iv47, will be closing this issue.

**Comment by jesualex** [comment]
@akshay2211 thanks!
