### ISSUE TITLE
Feature Request - Camera zoom

### ISSUE THREAD

**Issue by iv47** [akshay2211/PixImagePicker#28]
Zooming in/out before image capture, especially with rear camera, is a pretty handy feature.

**Comment by akshay2211** [comment]
Hello @iv47,
Thank you for giving pix a try and pointing out the necessary feature,

**Comment by iv47** [comment]
Trying out version `1.2.4` now.

**Comment by akshay2211** [comment]
yes, it can be done but ill be able to provide it by next month.
