### ISSUE TITLE
    implementation  'io.ak1.pix:piximagepicker:1.6.3' giving me old classes

### ISSUE THREAD

**Issue by amantheshooter** [akshay2211/PixImagePicker#286]
**    implementation  'io.ak1.pix:piximagepicker:1.6.3' giving me old classes**

When I am implementing 'io.ak1.pix:piximagepicker:1.6.3' this is giving me old classes, also on grade.properties showing VERSION_NAME=1.6.1

I thought its not published yet

**Comment by akshay2211** [comment]
Hi @amantheshooter ,
the latest version is indeed [1.6.3](https://github.com/akshay2211/PixImagePicker/blob/fa57762ee2028527314c90ded3d5067f16337866/pix/gradle.properties#L3), which does not contain the latest source.
i will be releasing version 1.6.4 with all the latest changes by the end of this week.

**Comment by akshay2211** [comment]
Hey @amantheshooter 
The new version of our PixImagePicker library has been released and is now ready for use.
kindly check [1.6.5](https://github.com/akshay2211/PixImagePicker?tab=readme-ov-file#download)

**Comment by amantheshooter** [comment]
Thanks @akshay2211
