### ISSUE TITLE
New Release???

### ISSUE THREAD

**Issue by amirisback** [akshay2211/PixImagePicker#287]
Are you still developing this library? If yes, when will the latest update be released?

**Comment by akshay2211** [comment]
Hello @amirisback, 
Yes, but due to scarcity of time, i am not able to actively update this lib. 
You will be getting a new release by end of next week.

**Comment by amirisback** [comment]
Happy For Hear That

**Comment by akshay2211** [comment]
Hey @amirisback 
The new version of our PixImagePicker library has been released and is now ready for use.
kindly check [1.6.5](https://github.com/akshay2211/PixImagePicker?tab=readme-ov-file#download)
