### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by kishanverma26** [akshay2211/PixImagePicker#29]
`

android.hardware.Camera.<init> (Camera.java:653)
--
  | android.hardware.Camera.open (Camera.java:494)
  | com.wonderkiln.camerakit.Camera1.openCamera (Camera1.java:667)
  | com.wonderkiln.camerakit.Camera1.start (Camera1.java:124)
  | com.wonderkiln.camerakit.CameraView$2.run (CameraView.java:266)
  | android.os.Handler.handleCallback (Handler.java:815)
  | android.os.Handler.dispatchMessage (Handler.java:104)
  | android.os.Looper.loop (Looper.java:210)
  | android.os.HandlerThread.run (HandlerThread.java:61)

`
How to fix this help me .This issue occurs in particular phones  
like :-Oppo android version 5.1

**Comment by akshay2211** [comment]
Hello @kishanverma26, Kindly use the latest version on the library.

**Comment by kishanverma26** [comment]
@akshay2211  thank you
