### ISSUE TITLE
Color of FAB in camera preview mode doesn't match custom color

### ISSUE THREAD

**Issue by nishinraj** [akshay2211/PixImagePicker#35]
Thanks for this awesome library. This is exactly what I need right now.
I've 2 issues though, I'll add it as two separate issues here.
1 - The FAB that shows selection count, When we select photos from the horizontal list in camera preview mode, doesn't match the color that I set in colors.xml. It's always dark green.

**Comment by akshay2211** [comment]
Hello @nishinraj
Thank you for trying out Pix.
This issue is been resolved in the latest release 1.2.5
