### ISSUE TITLE
Spacing required for Actionbar title in Gallery Mode

### ISSUE THREAD

**Issue by nishinraj** [akshay2211/PixImagePicker#36]
In gallery mode, when I select 1 photo, action bar title shows "Selected 1". 
But when multiple photos are selected it shows "Selected3".
That is there's no spacing between "Selected" and "3".

**Comment by akshay2211** [comment]
Hello @nishinraj  
Thank you for trying out [Pix](https://github.com/akshay2211/PixImagePicker).
This issue is been resolved in the latest release [1.2.5](https://github.com/akshay2211/PixImagePicker#download)

**Comment by nishinraj** [comment]
Thank you for fixing it this quick. I'll check it out tomorrow
