### ISSUE TITLE
Feature request : Option to choose file path

### ISSUE THREAD

**Issue by nishinraj** [akshay2211/PixImagePicker#37]
I would like to specify the location of the captured image. Currently its stored in DCIM with other camera images. I would like to keep images captured by pix in my own app's directory (or any directory of my choice), just like whatsapp.
I hope that's not too much to ask. Thanks in advance

**Comment by akshay2211** [comment]
Hello @nishinraj 
thanks for using pix,
this feature is already been added in Pix.
