### ISSUE TITLE
Error when submit image 

### ISSUE THREAD

**Issue by muhamad-sidik** [akshay2211/PixImagePicker#40]
hi akhsay...thankx for this great library.
but i found trouble when submit image to server.
im using retrofit.

first : 
 ArrayList<String> returnValue = data.getStringArrayListExtra(Pix.IMAGE_RESULTS);
                    myAdapter.addImage(returnValue);

                    for (String s : returnValue) {
                        //Log.e("val", " ->  " + s);
                        Uri imageUri = Uri.fromFile(new File(s));// For files on device
                        Log.e("hello", "- " + imageUri.toString());
                        arrayList.add(imageUri);
                    }

then when submit button:
 if (arrayList != null) {
                // create part for file (photo, video, ...)
                for (int i = 0; i < arrayList.size(); i++) {
                    //Log.e("LIST", String.valueOf(arrayList.get(i)));
                    parts.add(prepareFilePart("video"+i, arrayList.get(i)));
                }
            }

parsing URI:

error here....
RequestBody requestFile =
                RequestBody.create(                        MediaType.parse(Objects.requireNonNull(getApplicationContext().getContentResolver().getType(fileUri))),
                        file
                );

================
java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:98)
        at id.klaklik.silaura.Activity.InputKeluhanActivity.prepareFilePart(InputKeluhanActivity.java:539)

**Comment by akshay2211** [comment]
Hey @muhamad-sidik 
Its not exactly a library bug.
