### ISSUE TITLE
onActivityResult not called in nested Fragment

### ISSUE THREAD

**Issue by abhinanduN** [akshay2211/PixImagePicker#54]
`onActivityResult` is not being called inside nested fragment.
Its a bug issue of google.
https://issuetracker.google.com/issues/36959611

 there's a workaround by calling `onActivityResult` in parent and also using `getParentFragment().startActivityForResult`

**Comment by abhinanduN** [comment]
Override onActivityResult on Parent Activity and call child fragments onActivityResult inside it

`@Override`
`public void onActivityResult(int requestCode, int resultCode, Intent data) {`
`        List<Fragment> fragments = getSupportFragmentManager().getFragments();`
`        if (fragments != null) {`
`            for (Fragment fragment : fragments) {`
`                fragment.onActivityResult(requestCode, resultCode, data);`
`            }`
`        }`
`    }`

You should use getFragmentManager if you are not using Support Fragments

**Comment by ahmermughal** [comment]
@abhinanduN Hi can you give sample code of the fragment? I am stuck on the same issue.
I am confused as to from where to call getParentFragment().startActivityForResult();
Please elaborate.
Thanks

**Comment by abhinanduN** [comment]
Hi @ahmermughal . Sorry for the late reply . I think i meant, use either of those 2.
I don't remember about it clearly. But checking one of the old project i found i used the method of overriding the `onActivityResult` . Just as i said in the previous comment.
That's the code inside the parent. In child fragment you don't have to change anything in `onActivityResult`. Hope it helps
