### ISSUE TITLE
Images low quality from gallery.

### ISSUE THREAD

**Issue by agonshehu** [akshay2211/PixImagePicker#55]
Whenever i select pictures from gallery images lose quality. There is some kind of bug on images taken from gallery.

**Comment by akshay2211** [comment]
@agonshehu 
added Quality feature in new version [1.3.0](https://github.com/akshay2211/PixImagePicker#usage)

**Comment by agonshehu** [comment]
I saw that you updated it and it works perfectly now. Thanks.
