### ISSUE TITLE
White background on Flash and front camera

### ISSUE THREAD

**Issue by CodeDruid13** [akshay2211/PixImagePicker#57]
Am getting a white background for the buttons specified. Is this a bug or something?

**Comment by akshay2211** [comment]
hello @CodeDruid13 can you attach screenshots

**Comment by CodeDruid13** [comment]
[
![screenshot_20190106-095657_house v2](https://user-images.githubusercontent.com/19711569/50733164-8de87100-1199-11e9-8cd8-7f30ef060ced.jpg)
](url)

**Comment by CodeDruid13** [comment]
Though the buttons work well

**Comment by CodeDruid13** [comment]
.
