### ISSUE TITLE
After Pick any Portrait image it shows as landscape  

### ISSUE THREAD

**Issue by BarmanInfo** [akshay2211/PixImagePicker#6]
After Pick any Portrait image it show landscape when I pick image from gallery but for camera its working fine.

**Comment by akshay2211** [comment]
Hello @BarmanInfo can u be a bit more specific about the issue , are you talking about the images shown in pix library or the images which you have selected and reverted as the url by pix ? can you share any screenshot to explain.

**Comment by BarmanInfo** [comment]
![device-2018-05-30-175339](https://user-images.githubusercontent.com/14937512/40719984-e5cc5630-6432-11e8-8c2f-354a3ad18fbf.png)
![device-2018-05-30-175446](https://user-images.githubusercontent.com/14937512/40719991-ebe5bf84-6432-11e8-943c-8f716ab6fcd3.png)

Please check the screenshot for reference. 

I select a portrait image from my gallery Images. Then in onActivityResult I got a file URI which show the image in landscape mode.

**Comment by akshay2211** [comment]
can u share your activity and adapter somewhere as I don't think its the libraries fault.

**Comment by BarmanInfo** [comment]
I already share the code in my previous comment..

**Comment by akshay2211** [comment]
Sorry can't help you with this much info.
I think its yours codes fault.

**Comment by BarmanInfo** [comment]
OK... Fine .. Just Ignore My Code.. I will share the screenshot of your demo Application .. Please Check Once.  
1. This is the original Image 
![device-2018-05-31-190116](https://user-images.githubusercontent.com/14937512/40821597-79975826-6585-11e8-9014-25a99a66a6e2.png)


Then just Open your Demo Application and pick the same Image 

![device-2018-05-31-190138](https://user-images.githubusercontent.com/14937512/40821611-97badd78-6585-11e8-924d-96662ad8ddca.png)
![device-2018-05-31-190228](https://user-images.githubusercontent.com/14937512/40821614-9f970fda-6585-11e8-854b-003c8e080705.png)

And Please Check the Result ......

![device-2018-05-31-190245](https://user-images.githubusercontent.com/14937512/40821633-b900d348-6585-11e8-97cb-05f99a726440.png)


Device : Samsung Device Galaxy On5 Pro or Any Samsung Device
Os Version: 7.1.1

**Comment by akshay2211** [comment]
its is a device specific issue , i  can provide a workaround for this problem
[https://stackoverflow.com/a/12933632](https://stackoverflow.com/a/12933632)
add this method in your adapter and you are good to go

**Comment by akshay2211** [comment]
Use this in your adapter where you are showing the image

    File f = new File(list.get(position));
    Bitmap scaled = com.fxn.utility.Utility.getScaledBitmap(512,  com.fxn.utility.Utility.getExcifCorrectedBitmap(f));
    ((Holder) holder).iv.setImageBitmap(scaled);

and use the latest version 1.0.4
