### ISSUE TITLE
Integrate record video!!!

### ISSUE THREAD

**Issue by dverdugo85** [akshay2211/PixImagePicker#60]
It would be interesting if you can add, record video !!!

**Comment by emailsubjekt** [comment]
He doesn't have to, it's really easy to do

**Comment by koeks525** [comment]
> He doesn't have to, it's really easy to do

Really, how so? Thought this was one of the features 'in the works'

**Comment by uplamartya** [comment]
How to Implement video recording??

**Comment by sagarnayak** [comment]
hi @akshay2211 
Great to hear that you are planning to integrate video recording and picking in this library. I suggest using MediaRecorder for this. I faced few limitations while starting video recording with intent. if the user wants to record video with specific length or specific size this is not possible in this way.
but this is possible with media recorder.

**Comment by akshay2211** [comment]
Hello @dverdugo85 @emailsubjekt @uplamartya @sagarnayak 
Thanks for using [Pix](https://github.com/akshay2211/PixImagePicker),
Video support feature is integrated in the [latest release](https://github.com/akshay2211/PixImagePicker#download).
