### ISSUE TITLE
fotoapparat uses obsolete kotlinx.coroutines.experimental - please update

### ISSUE THREAD

**Issue by mrimvo** [akshay2211/PixImagePicker#66]
There is a problem with the fotoapparat dependency of Pix, which uses obsolete classes in the `kotlinx.coroutines.experimental` package. Luckily, they already fixed it and also [Pix has already updated the dependency](https://github.com/akshay2211/PixImagePicker/blame/cf199fdb0b2ce51a5115b2b46d800fdf136e663d/pix/build.gradle#L40).

All we need is an update of Pix so it is available for download with gradle. We would like to kindly ask you to update the library. :)

**Comment by PriyaSindkar** [comment]
The commits are showing that fotoapparat is updated in pix version 1.2.5 but I am still getting the error:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/experimental/CompletableDeferredKt;
        at io.fotoapparat.hardware.CameraDevice.<init>(CameraDevice.kt:48)
```

**Comment by akshay2211** [comment]
@mrimvo 
updated in new Version [1.3.0](https://github.com/akshay2211/PixImagePicker#usage)
