### ISSUE TITLE
Unable to use pix with glide version 4.9.0 in my project

### ISSUE THREAD

**Issue by cresusjpt** [akshay2211/PixImagePicker#70]
after adding glide to the project, pix could not run (NoSuchMethodError ... RequestOptions override). But when I changed the version of glide to be the same as pix it was good but I need some glide features in the latest version.

**Comment by akshay2211** [comment]
@cresusjpt 
you can use the latest Version of Pix [1.3.0](https://github.com/akshay2211/PixImagePicker#usage), it has the latest version of [Glide](https://github.com/bumptech/glide)
