### ISSUE TITLE
SCREEN_ORIENTATION_REVERSE_PORTRAIT opening camera upside down

### ISSUE THREAD

**Issue by emailsubjekt** [akshay2211/PixImagePicker#72]
How do you get back camera instead of front camera? I've tried BEHIND, SCREEN_ORIENTATION_REVERSE_PORTRAIT and SCREEN_ORIENTATION_PORTRAIT. Reverse portrait is showing the Interface upside down?! What's the point of that? Also how do you get the back camera first. And then switch to front camera with the switch

**Comment by akshay2211** [comment]
Hey @emailsubjekt,
CREEN_ORIENTATION_REVERSE_PORTRAIT and SCREEN_ORIENTATION_PORTRAIT both and remaining are default orientation provided by android.
you can set
`.setScreenOrientation(Options.SCREEN_ORIENTATION_FULL_SENSOR)  `
for default sensor dependent orientation.

And there is a method in the documentation 
` .setFrontfacing(true)  `
kindly set it to false or remove this param for front facing camera view.

**Comment by congdanh1608** [comment]
Hi @akshay2211 
This method has an issue:
.setFrontfacing(true)
Look like you forgot set front facing camra when initialize on Pix.java.

**Comment by akshay2211** [comment]
Hello @congdanh1608 
Thank you for pointing out the bug 
it has been removed in the [latest](https://github.com/akshay2211/PixImagePicker#download) version.
