### ISSUE TITLE
Error: Program type already present: com.google.common.util.concurrent.ListenableFuture

### ISSUE THREAD

**Issue by pingothedoer** [akshay2211/PixImagePicker#73]
I have tried to add your lib but facing this issue.

AGPBI: {"kind":"error","text":"Program type already present: com.google.common.util.concurrent.ListenableFuture","sources":[{}],"tool":"D8"}
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForStageDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Program type already present: com.google.common.util.concurrent.ListenableFuture
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

I have searched for different solutions and found this one, add these lines in root build.gradle file. But it didn't work.

`configurations {
    all*.exclude group: 'com.google.guava', module: 'listenablefuture'
}`

**Comment by akshay2211** [comment]
I suggest this is not the library issue but a Multidex one.
if anything still comes up feel free to reopen the issue.
