### ISSUE TITLE
Solved: Bug duplicate the last picture of the gallery

### ISSUE THREAD

**Issue by Qism0** [akshay2211/PixImagePicker#74]
Hi,

thank you @akshay2211  and the team for the amazing work you have been doing here, I am down for helping maintaining the project and helping resolving issues.

I noticed a duplicate last picture that I solved in my fork, maybe I missed something but I think the limit in Pix.java has to be `cursor.length() - 1` doesn't it?

https://github.com/akshay2211/PixImagePicker/pull/63/commits/c7b2b23f1f7b753549ca78ba95f5a7e357c0b4f6

Regards
73k05

**Comment by akshay2211** [comment]
hey @Qism0 
Thank you for trying out and contribution in [PixImagePicker
](https://github.com/akshay2211/PixImagePicker)
this bug is resolved in the latest release [1.3.1](https://github.com/akshay2211/PixImagePicker#download).

**Comment by Qism0** [comment]
Cool thanks!
