### ISSUE TITLE
Gradle 3.4.0

### ISSUE THREAD

**Issue by Bavneet6** [akshay2211/PixImagePicker#75]
error: package kotlin does not exist
error: cannot find symbol class Function1

**Comment by akshay2211** [comment]
Hello @Bavneet6 
Thank you for trying out [PixImagePicker
](https://github.com/akshay2211/PixImagePicker)
Kindly check the latest update [1.3.1](https://github.com/akshay2211/PixImagePicker#download)
bug is been resolved
