### ISSUE TITLE
Image or Camera selection option

### ISSUE THREAD

**Issue by RameshbabuJaga** [akshay2211/PixImagePicker#76]
Hi thanks for the awesome library and still am using this in my projects and am looking for only option is before showing camera directly, we need to show an alert popup saying from **Gallery** or **Camera** and based on user selection it would open that directly. If this option is there means it will be more friendly.  Also gallery right now it showing whole list of images. For users its very difficult to find their images at right time. They would have keep on searching for the specific image. Better it would be folder wise as one option. So that they can find it in a short span of time. Hope you understood from user point of view.

**Comment by akshay2211** [comment]
Hey @RameshbabuJaga,
Thank you for using Pix and providing valuable suggestions.
I will surely add this sort of functionality in coming days.

**Comment by DhanalakshmiS** [comment]
Hey @akshay2211 ,

Thank you for the awesome library. I would also like the option what @RameshbabuJaga has suggested. And also it will be better, if you can provide multiple camera image upload directly.(not from gallery)
