### ISSUE TITLE
setPreSelectedUrls(list) for camera only return single image url?

### ISSUE THREAD

**Issue by pawarn** [akshay2211/PixImagePicker#77]
When we select multiple images from the gallery with setPreSelectedUrls(imgList) method return old selected image as well as the newly selected image URL.

But same behavior not working with multiple image capture from camera. It only returns the latest capture single image URL.

What I expect is it should return a previoously selected image URLs with a new captured image URL using setPreSelectedUrls(imgList).

**Comment by abroresonaliyev** [comment]
> When we select multiple images from the gallery with setPreSelectedUrls(imgList) method return old selected image as well as the newly selected image URL.
> 
> But same behavior not working with multiple image capture from camera. It only returns the latest capture single image URL.
> 
> What I expect is it should return a previoously selected image URLs with a new captured image URL using setPreSelectedUrls(imgList).

I think need remove `selectionList.clear();` row on taken photo
in next code

`  private void onClickMethods() {
        findViewById(R.id.clickme).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                fotoapparat.takePicture().toBitmap().transform(new Function1<BitmapPhoto, Bitmap>() {
                    @Override
                    public Bitmap invoke(BitmapPhoto bitmapPhoto) {
                        fotoapparat.stop();
                        return Utility.rotate(bitmapPhoto.bitmap, -bitmapPhoto.rotationDegrees);
                    }
                }).whenAvailable(new Function1<Bitmap, Unit>() {
                    @Override
                    public Unit invoke(Bitmap bitmap) {
                        if (bitmap != null) {
                            synchronized (bitmap) {
                                File photo = Utility.writeImage(bitmap, options.getPath(), options.getImageQuality(), options.getWidth(), options.getHeight());
                                selectionList.clear();
                                selectionList.add(new Img("", "", photo.getAbsolutePath(), ""));
                                returnObjects();

                            }
                        }
                        return null;
                    }
                });
            }
        });`

**Comment by abroresonaliyev** [comment]
> > When we select multiple images from the gallery with setPreSelectedUrls(imgList) method return old selected image as well as the newly selected image URL.
> > But same behavior not working with multiple image capture from camera. It only returns the latest capture single image URL.
> > What I expect is it should return a previoously selected image URLs with a new captured image URL using setPreSelectedUrls(imgList).
> 
> I think need remove `selectionList.clear();` row on taken photo
> in next code
> 
> `
> 
> ```
>             fotoapparat.takePicture().toBitmap().transform(new Function1<BitmapPhoto, Bitmap>() {
>                 @Override
>                 public Bitmap invoke(BitmapPhoto bitmapPhoto) {
>                     fotoapparat.stop();
>                     return Utility.rotate(bitmapPhoto.bitmap, -bitmapPhoto.rotationDegrees);
>                 }
>             }).whenAvailable(new Function1<Bitmap, Unit>() {
>                 @Override
>                 public Unit invoke(Bitmap bitmap) {
>                     if (bitmap != null) {
>                         synchronized (bitmap) {
>                             File photo = Utility.writeImage(bitmap, options.getPath(), options.getImageQuality(), options.getWidth(), options.getHeight());
>                             selectionList.clear();
>                             selectionList.add(new Img("", "", photo.getAbsolutePath(), ""));
>                             returnObjects();
> 
>                         }
>                     }
>                     return null;
>                 }
>             });
>        `
> ```

@akshay2211 what you say?

**Comment by abroresonaliyev** [comment]
> > When we select multiple images from the gallery with setPreSelectedUrls(imgList) method return old selected image as well as the newly selected image URL.
> > But same behavior not working with multiple image capture from camera. It only returns the latest capture single image URL.
> > What I expect is it should return a previoously selected image URLs with a new captured image URL using setPreSelectedUrls(imgList).
> 
> I think need remove `selectionList.clear();` row on taken photo
> in next code
> 
> `
> 
> ```
>             fotoapparat.takePicture().toBitmap().transform(new Function1<BitmapPhoto, Bitmap>() {
>                 @Override
>                 public Bitmap invoke(BitmapPhoto bitmapPhoto) {
>                     fotoapparat.stop();
>                     return Utility.rotate(bitmapPhoto.bitmap, -bitmapPhoto.rotationDegrees);
>                 }
>             }).whenAvailable(new Function1<Bitmap, Unit>() {
>                 @Override
>                 public Unit invoke(Bitmap bitmap) {
>                     if (bitmap != null) {
>                         synchronized (bitmap) {
>                             File photo = Utility.writeImage(bitmap, options.getPath(), options.getImageQuality(), options.getWidth(), options.getHeight());
>                             selectionList.clear();
>                             selectionList.add(new Img("", "", photo.getAbsolutePath(), ""));
>                             returnObjects();
> 
>                         }
>                     }
>                     return null;
>                 }
>             });
>        `
> ```


@pawarn 
it's `selectionList.clear();` helped me

**Comment by akshay2211** [comment]
Hello @pawarn , @abroresonaliyev 
Thank you  for trying out Pix
this bug is been resolved in the latest version [1.4.4](https://github.com/akshay2211/PixImagePicker#download)

**Comment by pawarn** [comment]
Thanks for the answer I will try this.
Thanks for the awesome library.
