### ISSUE TITLE
Gradle Version

### ISSUE THREAD

**Issue by FizzyCodeSolutions** [akshay2211/PixImagePicker#78]
Hey,

Which version of glide gradle you are using? its creating issue in my project.

java.lang.AbstractMethodError: abstract method "void com.bumptech.glide.module.RegistersComponents.registerComponents(android.content.Context, com.bumptech.glide.Glide, com.bumptech.glide.Registry)"

**Comment by akshay2211** [comment]
Hello @FizzyCodeSolutions,
Thank you for trying out Pix
I am using glide version 4.9.0

**Comment by FizzyCodeSolutions** [comment]
are you planning to support video as well in future?

**Comment by akshay2211** [comment]
yes after a few months.
