### ISSUE TITLE
pass data to the onActivityResult

### ISSUE THREAD

**Issue by jpainam** [akshay2211/PixImagePicker#83]
Hi, I want to pass data back to the activity that implements `onActivityResult`. I called `Pix.start` from another class which cannot implement onActivityResult. I'm able to execute `onActivityResult`, but I need to sent data to that method. I know we usually used `setResult(...; intent)`. But Pix doesn't allow setting our own intent.

Pls, How can I achieve this?

Thank you

**Comment by akshay2211** [comment]
Hello @jpainam 
Instead of adding the library path in your gradle file 
you can import the library as a module in your project and implement this kind of customization.
