### ISSUE TITLE
Are you planning to add video support in the future?

### ISSUE THREAD

**Issue by AzarouAmine** [akshay2211/PixImagePicker#90]
Hey there, are you planning to integrate a video picker with this library in the future. I'm developing a whatsapp-like application and this library is the perfect fit, I've been using it so far and would love to know if a video picker is planned anytime soon.

**Comment by akshay2211** [comment]
Hello @AzarouAmine 
Yes , Video Picker integration is planned in next few months.

**Comment by koeks525** [comment]
@akshay2211 Thank you so much!

**Comment by akshay2211** [comment]
Hello @AzarouAmine @koeks525 
Thanks for using [Pix](https://github.com/akshay2211/PixImagePicker),
Video support feature is integrated in the [latest release](https://github.com/akshay2211/PixImagePicker#download).
