### ISSUE TITLE
how get uri selected image in array

### ISSUE THREAD

**Issue by 3nbaessam** [akshay2211/PixImagePicker#93]

**Comment by akshay2211** [comment]
Hey @3nbaessam 
to get uri you can just convert it into uri by `Uri.parse("image url" )`

 `ArrayList<String> returnValue = data.getStringArrayListExtra(Pix.IMAGE_RESULTS);`
`//1st image `
`Uri  uri = Uri.parse(returnValue.get(0))`

**Comment by LebonNic** [comment]
You need to do this in Kotlin:

```
 val uris = returnValue.map { path ->
    Uri.parse("file://${path}")
 }
```

The prefix "file://" is important.
