### ISSUE TITLE
No Custom Toast

### ISSUE THREAD

**Issue by MukulPrabhakar** [akshay2211/PixImagePicker#96]
Unable to add Custom Popup for Image Count> Max Pick Image

**Comment by akshay2211** [comment]
Hello @MukulPrabhakar 
You can pull the whole library and customize it if you want.
or if you just want to change the text of the message you can 
add this in you strings.xml
`<string name="selection_limiter_pix">Can\'t select more than %d items.</string>`
and customize the message as you want.
