### ISSUE TITLE
Can't click multiple Images like in whatsapp

### ISSUE THREAD

**Issue by jimmy-jose** [akshay2211/PixImagePicker#99]
Is there any way to click multiple images as just like in whatsapp?

**Comment by akshay2211** [comment]
Hello @jimmy-jose 
Thanks for trying PixImagePicker
Just long press on any image for selecting multiple images.

**Comment by jimmy-jose** [comment]
Hey @akshay2211 Thanks for replaying fast. But I wanted to take multiple pictures from the camera. Not from the gallery. Is that possible?

**Comment by akshay2211** [comment]
But multiple image from camera is not available in WhatsApp right?
You can create a image viewing screen which shows image after clicking and have a option to again open image picker  and add another pic.

**Comment by jimmy-jose** [comment]
So on the bottom left corner of the viewing screen there is a button to add add more images

**Comment by akshay2211** [comment]
Hey @jimmy-jose 

> 

So on the bottom left corner of the viewing screen there is a button to add add more images
--


You are talking about the second screen that WhatsApp provides to edit images 
but [PixImagePicker](https://github.com/akshay2211/PixImagePicker) is currently just a image picker.
you can create the second screen by your own , just open [PixImagePicker](https://github.com/akshay2211/PixImagePicker) again from the left corner button of your own image editing screen.
